build: false

environment:
  matrix:
    - MINICONDA: "C:\\Miniconda36-x64"
      PYTHON: 3.6

install:
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt

test_script:
  - psexec.exe -l -d "python setup.py test"
